Fix the crash of Responsive Activity
On a large tablet, app crashes when the orientation is changed
from portrait to landscape.

This was caused because of the error below.

java.lang.IllegalArgumentException: Wrong state class,
expecting View State but received class
androidx.drawerlayout.widget.DrawerLayout$SavedState instead.
This usually happens when two views of different type
have the same id in the same hierarchy. This view's id
is id/activity_container. Make sure other views do not use the same id.

The fix should be to use the same view type for the same
view id. (The DrawerLayout in the layout/activity_main.xml
and layout-w600dp/activity_main.xml need to be wrapped by
FrameLayout because the root layout of the layout-w1240dp
uses FrameLayout as its root view instead of DrawerLayout)

Bug: 184008474
Test: TemplateTest, manually verified the created project on a large
tablet and changed the orientation from portrait to landscape

Change-Id: I4f855bd191853fc2c6dadb273995935b3415d548

Former-commit-id: 5268db3691144c43360c8faf033406381c50325d