Fix the crash of primary/detail template in below API level 23
- View.OnContextClickListener is introduced in API level 23.
  Change the code to reference it only with API level 23+.
- Stop assigning a lambda to a variable as it seems not supported in API
level 16
  java.lang.NoClassDefFoundError: com.example.android.myapplication.ItemListFragment-$$ExternalSyntheticLambda1
        at com.example.android.myapplication.ItemListFragment.onViewCreated(ItemListFragment.java:105)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)

Bug: 187032091
Test: TemplateTest. Manually verified the app with API level 16
Change-Id: I538867d0c57819aa2fc19e1c0beb3829694db70f

Former-commit-id: 1249f95145dcf17c3182deb1f79e93339c83b556