Update JPS metadata for sdkrepository
Without this fix, I can't run lint tests from within tool/base;
any test that touches the SDK repository will throw
java.lang.NoClassDefFoundError: com/sun/istack/FinalArrayList

Everything works from Bazel and Gradle, so it looks like the
dependency on istack-commons-runtime that is listed for jaxb-runtime
in Bazel is missing from JPS.

Test: Running lint tests from within the IDE
Bug: N/A
Change-Id: Ifa246ff06dea6a301e238fc04be92fd5ebb19603

Former-commit-id: 5ecdbee0df350a92ccc2c0be3680c95a9e054e27