Fix path to slicer header files in slicer BUILD file.
The relative path to the slicer header files was wrong, and thus failing on the
bazel foundry bot. e.g.

[0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
ERROR: /usr/local/google/home/android-devtools-build/.cache/bazel/
  _bazel_android-devtools-build/26508b8ba17e16b402f042900d3d5eb7/external/
  slicer_repo/BUILD.bazel:3:1: Couldn't build file external/slicer_repo/_objs/
  slicer/external/slicer_repo/bytecode_encoder.o:
  C++ compilation of rule '@slicer_repo//:slicer' failed (Exit 1)
external/slicer_repo/bytecode_encoder.cc:17:10: fatal error:
  'slicer/bytecode_encoder.h' file not found

Bug: 72179763
Test: Run with RBE (remote bazel invocation):
      ./tools/base/bazel/bazel build --config=remote -- @slicer_repo//:slicer

Change-Id: I48c2f823230b7762b602644b087f06409971f1bd

Former-commit-id: 5f56cc774a22651fcc89499b6b7312505cb73a1c