[Aapt Kotlin] BlameLogger for ResourceCompiler.
Added a Logger that can rewrite Sources on the fly as errors/warnings
are being logged. The key reason to do it this way is that the Aapt2
exception rewrite method is limiting, allowing something of the format:

ERROR: <file> <line?> <column?> <message>

A primary use case where this is insufficient is a resource being
redefined. I.e.

ERROR: <file>.xml line:32, column: 12 @string/foo has already been
defined. It's original definition is <file>.xml line:12, column: 12.

Where multiple sources adds clarity to the error, thus BlameLogger
allows for multiple sources, and for them to be transformed I.e.

logger.error(null, "%1$s %3$s has already been defined. It's original
definition is here: %2$s", currentSource, originalSource, resourceName)

Bug: 139297538
Test: testing will be added later, once the logger is wired up.
Change-Id: Ibcbaf258c83160fabd3f21ab74735b1e8244dabc

Former-commit-id: 8aecd9a061f9359e5e48a77e5181dfee86dc2dd8