jarjar parts of gRPC too
After commit 2be8b53b, IntelliJ bundles its own version of gRPC:
https://github.com/JetBrains/intellij-community/commit/2be8b53b
This is done as part of a broader set of changes to support
https://youtrack.jetbrains.com/issue/CPP-22344

Without this change, many of our tests fail with a linkage error:
java.lang.NoSuchMethodError: 'io.grpc.MethodDescriptor$Marshaller io.grpc.protobuf.ProtoUtils.marshaller(com.android.tools.idea.protobuf.Message)'
	at com.android.tools.deployer.devices.FakeDeviceServiceGrpc.getGetAppUidMethod(FakeDeviceServiceGrpc.java:50)

Bug: 176938468
Test: existing
Change-Id: I18c09ce7da8010fd9d66a74905dc2380c09c9bc7

Former-commit-id: c1e47129350bb1e74e19b945eee56e235d33393e