Enable more tests under //tools
Some tests are still excluded due to test failure. The failing targets are:

* //tools/adt/idea/android-lang:intellij.android.lang.tests_tests
  error: https://paste.googleplex.com/4846097514102784

* //tools/adt/idea/profilers-ui:intellij.android.profilers.ui_tests
  error: https://paste.googleplex.com/4911930772815872

* //tools/base/build-system/integration-test/...
  sample error: https://paste.googleplex.com/5893557065875456

Test: Manually on Macbook
Bug: 141646507
Change-Id: Id2516cef010d0cd25bd9f39dc1969511948a9ea4

Former-commit-id: e6340ee4bdbb439aadda3bb623770e623fb8213f